Repository siddharthkp/react-ui, pull requests merged in 2020-05, with the labels that each got.

#52 Use bundlesize2 preview
  packages/react-ui/package.json
  yarn.lock
Labels: dependencies

#53 Docs: Add size docs for Text
  packages/docs/src/pages/components/text.js
  packages/react-ui/package.json
  yarn.lock
Labels: docs

#57 Add changelog for beta.25
  packages/docs/src/components/list.js
  packages/docs/src/pages/changelog/index.js
  packages/react-ui/src/components/stack/index.js
Labels: docs

#47 Docs: Change favicon based on theme
  packages/docs/public/favicon-base.png
  packages/docs/public/favicon-dark.png
  packages/docs/public/favicon-light.png
  packages/docs/public/index.html
  packages/docs/src/App.js
Labels: docs

#39 Adding Dialog component
  packages/docs/src/App.js
  packages/docs/src/pages/components/dialog.js
  packages/docs/src/pages/index.js
  packages/react-ui/index.js
  packages/react-ui/package.json
  packages/react-ui/src/components/dialog/dialog.styles.js
  packages/react-ui/src/components/dialog/index.js
  packages/react-ui/src/components/theme-provider/index.js
  packages/react-ui/src/themes/base.js
  packages/react-ui/src/themes/dark.js
  packages/react-ui/src/themes/light.js
  yarn.lock
Labels: component

#64 Tweak designs for modal a bit
  packages/docs/src/pages/components/dialog.js
  packages/react-ui/src/themes/base.js
  packages/react-ui/src/themes/dark.js
  packages/react-ui/src/themes/light.js
Labels: enhancement

#48 #41: Add example docs for reach-ui.
  .gitignore
  packages/docs/package.json
  packages/docs/src/App.js
  packages/docs/src/pages/core-concepts/index.js
  packages/docs/src/pages/core-concepts/integrating-with-reach-ui.js
  packages/docs/src/pages/index.js
  yarn.lock
Labels: docs

#65 Simplify page for using reach ui
  packages/docs/package.json
  packages/docs/src/pages/core-concepts/index.js
  packages/docs/src/pages/core-concepts/integrating-with-reach-ui.js
  yarn.lock
Labels: docs

#60 New component: Tooltip
  packages/docs/src/App.js
  packages/docs/src/pages/components/index.js
  packages/docs/src/pages/components/tooltip.js
  packages/docs/src/pages/index.js
  packages/react-ui/index.js
  packages/react-ui/package.json
  packages/react-ui/src/components/theme-provider/index.js
  packages/react-ui/src/components/tooltip/index.js
  packages/react-ui/src/components/tooltip/tooltip.styles.js
  packages/react-ui/src/themes/base.js
  packages/react-ui/src/themes/dark.js
  packages/react-ui/src/themes/light.js
  yarn.lock
Labels: component

#69 Sync reach component versions
  packages/docs/package.json
  packages/react-ui/package.json
  yarn.lock
Labels: dependencies, enhancement

#71 Alert component
  packages/docs/src/App.js
  packages/docs/src/pages/components/alert.js
  packages/docs/src/pages/components/index.js
  packages/docs/src/pages/index.js
  packages/react-ui/index.js
  packages/react-ui/package.json
  packages/react-ui/src/components/alert/alert.styles.js
  packages/react-ui/src/components/alert/index.js
  packages/react-ui/src/components/button/index.js
  packages/react-ui/src/themes/base.js
  packages/react-ui/src/themes/dark.js
  packages/react-ui/src/themes/light.js
  yarn.lock
Labels: component

#76 Add tabs component
  packages/docs/src/App.js
  packages/docs/src/components/page.js
  packages/docs/src/pages/components/index.js
  packages/docs/src/pages/components/tabs.js
  packages/docs/src/pages/index.js
  packages/react-ui/index.js
  packages/react-ui/package.json
  packages/react-ui/src/components/button/button.styles.js
  packages/react-ui/src/components/tabs/index.js
  packages/react-ui/src/components/tabs/tabs.styles.js
  packages/react-ui/src/components/theme-provider/index.js
  packages/react-ui/src/primitives/element.js
  packages/react-ui/src/themes/base.js
  packages/react-ui/src/themes/dark.js
  packages/react-ui/src/themes/light.js
  yarn.lock
Labels: component

#78 Add skeleton component
  packages/docs/src/App.js
  packages/docs/src/pages/components/index.js
  packages/docs/src/pages/components/skeleton.js
  packages/docs/src/pages/index.js
  packages/react-ui/index.js
  packages/react-ui/src/components/skeleton/index.js
  packages/react-ui/src/components/skeleton/skeleton.styles.js
  packages/react-ui/src/themes/base.js
  packages/react-ui/src/themes/dark.js
  packages/react-ui/src/themes/light.js
Labels: component

#79 handle 0 for margin values
  packages/react-ui/src/primitives/element.js
Labels: bug

#81 Test: remove margin 0
  packages/react-ui/src/components/checkbox/checkbox.styles.js
  packages/react-ui/src/components/checkbox/index.js
  packages/react-ui/src/primitives/element.js
Labels: enhancement

#85 update version to fix tests + docs
  packages/docs/package.json
  packages/visual-tests/package.json
Labels: bug
