Repository siddharthkp/react-ui, pull requests merged in 2020-04, with the labels that each got.

#32 Theme fixes:
  packages/react-ui/src/themes/base.js
  packages/react-ui/src/themes/dark.js
  packages/react-ui/src/themes/light.js
Labels: enhancement

#21 Add support for RTL layouts in <Stack/> by using logical margin
  packages/react-ui/src/components/stack/index.js
  packages/react-ui/src/primitives/interpolate.js
Labels: enhancement

#19 Fix scrollbar bug in example.js
  packages/docs/src/components/example.js
Labels: docs

#35 Fix staging deployment with now
  packages/docs/package.json
  packages/docs/src/App.js
  packages/react-ui/index.js
  packages/react-ui/package.json
  packages/react-ui/rollup.config.js
  yarn.lock
Labels: bug, enhancement

#33 add forwardRef to all components
  packages/ecosystem/stats/index.js
  packages/react-ui/src/components/avatar/index.js
  packages/react-ui/src/components/breadcrumb/index.js
  packages/react-ui/src/components/button/index.js
  packages/react-ui/src/components/card/index.js
  packages/react-ui/src/components/form/index.js
  packages/react-ui/src/components/grid/index.js
  packages/react-ui/src/components/heading/index.js
  packages/react-ui/src/components/image/index.js
  packages/react-ui/src/components/input/index.js
  packages/react-ui/src/components/link/index.js
  packages/react-ui/src/components/menu/index.js
  packages/react-ui/src/components/paragraph/index.js
  packages/react-ui/src/components/select/index.js
  packages/react-ui/src/components/spinner/index.js
  packages/react-ui/src/components/stack/index.js
  packages/react-ui/src/components/switch/index.js
  packages/react-ui/src/components/text/index.js
  packages/react-ui/src/components/textarea/index.js
Labels: bug

#36 Added fullwidth to the button prop
  packages/docs/src/pages/components/button.js
  packages/react-ui/src/components/button/index.js
Labels: enhancement
